query bookings($filter: BookingFilterInput, $pagination: PaginationInput) {
  bookings(filter: $filter, pagination: $pagination) {
    total
    error
    ok
    bookings {
      id
      kind
      start
      end
      user {
        id
        name
        email
      }
      car {
        id
        model
        color
      }
      status
      office {
        id
        name
        latitude
        longitude
      }
      createdAt
      updatedAt
    }
  }
}

query booking($id: ID!) {
  booking(id: $id) {
    booking {
      id
      kind
      start
      end
      user {
        id
        name
        email
      }
      car {
        id
        model
        color
      }
      status
      office {
        id
        name
        latitude
        longitude
      }
      createdAt
      updatedAt
    }
    error
    ok
  }
}
