query cars($pagination: PaginationInput) {
  cars(pagination: $pagination) {
    cars {
      id
      price
      make
      model
      year
      color
      description
      images
      createdAt
      updatedAt
    }
    total
    ok
    error
  }
}
