query offices($pagination: PaginationInput) {
  offices(pagination: $pagination) {
    offices {
      id
      name
      description
      address
      phone
      email
      createdAt
      updatedAt
    }
    total
    ok
    error
  }
}
